### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by jpobley** [highcharts/adapt-chart-to-legend#6]
I'm getting this error in a couple places and can't figure out why:

`Uncaught TypeError: Cannot set property 'translateY' of undefined (adapt-chart-to-legend.js:18)`

The chart still draws, but it seems to throw that error (which stops my script execution). The plugin is looking for `alignAttr`, and I can't figure out when the group will and will not have that attribute.

Any suggestions?

**Comment by rishijoshi** [comment]
Same issue. 
The charts don't render for me at all.
dependencies.js:102 TypeError: Cannot set property 'translateY' of undefined

**Comment by TorsteinHonsi** [comment]
Can you reproduce that from http://jsfiddle.net/highcharts/haB8y/?

**Comment by rishijoshi** [comment]
adding a check fixed the error. Thanks.
if (this.group.alignAttr) {
    this.group.alignAttr.translateY = translateY;
}
