### ISSUE TITLE
Exporting to image file truncates chart

### ISSUE THREAD

**Issue by foxprorawks** [highcharts/adapt-chart-to-legend#7]
When using this plugin, exports to jpg etc. truncate the image - see attached file.
![chart](https://cloud.githubusercontent.com/assets/16322155/13463614/f76afce0-e084-11e5-9ca6-6346dcf5a2d5.jpeg)

**Comment by arvel** [comment]
Also seeing the same issue:

![energysavingsovertimebyproject png 1](https://cloud.githubusercontent.com/assets/202785/13646468/77d5f0d8-e5e4-11e5-89cf-01b13d12bbdf.png)

**Comment by TorsteinHonsi** [comment]
Live demo, (where the current plugin code is pasted inside the fiddle): http://jsfiddle.net/goLeqnjj/

**Comment by arvel** [comment]
@TorsteinHonsi actually that live demo in the jsfiddle provided is broken in the same way as described above.  See the legend in this exported image (reproduced in Firefox, Safari, and Chrome):

![chart-7](https://cloud.githubusercontent.com/assets/202785/13678641/980421ac-e6a4-11e5-8c49-b7636604d9e3.png)

**Comment by TorsteinHonsi** [comment]
Yes, it is a live demo of the bug, not the fix. Sorry for the miscommunication. In [this fiddle](http://jsfiddle.net/goLeqnjj/2/), the fix is applied.

**Comment by foxprorawks** [comment]
Hi - do you know when this change will be part of an official release?

**Comment by TorsteinHonsi** [comment]
It is already. It is the plugin version 1.0.3. Highcharts itself is not affected.

**Comment by foxprorawks** [comment]
Thanks.
