### ISSUE TITLE
Problem with plugin while adding series dynamically 

### ISSUE THREAD

**Issue by rohithra** [highcharts/adapt-chart-to-legend#8]
Here the jsfiddle http://jsfiddle.net/rohithra/5L66og4r/

**Comment by rohithra** [comment]
the legend is not aligning properly initially. Like when adding a second series in this example http://jsfiddle.net/rohithra/LpL166o6/ the legend is misaligned but works fine later.

**Comment by TorsteinHonsi** [comment]
Can you set a specific width of the chart in order to reliably reproduce that?
